.yamllint.yml

This is considered invalid:
```
foo: 
bar:  true
```
But this is considered valid:
```
foo: 
bar:  true
```
I don't think the linter should force ordering of comments for a particular indentation level.

YAMLLINT: Disable comments-indentation

---

.github/actions/lint-yaml/action.yml

I'm not seeing the github annotations show up for yaml lint https://github.com/abcxyz/binary-integrity-multi-repo-poc/pull/8. This should force the format to be compatible with github annotations.

fix: force github format for yamllint

---

.github/workflows/.lint-actions.yml
.github/workflows/lint.yml

Now that we are not initializing we do not need to set a default dir. Both the terraform fmt and lint discover all terraform files.
NOTE: We might need to add a way to ignore certain directories like templates.
Should resolve: https://github.com/abcxyz/abcxyz-services/pull/190

chore: do not set default terraform directory

---

.github/workflows/.lint-actions.yml
.github/workflows/lint.yml

1. Automatically detect the location of go.mod files
2. Expand go linting to run on a matrix - one job for every go.mod file
3. Run both the lint-go and lint-go-modules actions in the same job instead of separate jobs but gate with `if: always()` so both always run even if one fails.
Tested here: https://github.com/abcxyz/authz-tooling/pull/49. Execution example: https://github.com/abcxyz/authz-tooling/actions/runs/14577191250/job/40885807108?pr=49
Also confirmed it works on pkg https://github.com/abcxyz/pkg/actions/runs/14578091812/job/40888563207?pr=444

feat: detect go.mod path

---

.github/workflows/.lint-actions.yml

Do not re-run lint-actions if the PR is edited.

chore: no triggers for pr on lint-actions

---

.github/actions/lint-terraform/action.yml

Right now we fail immediately if your terraform fmt is incorrect. We should also still run the terraform lint checks so you can see both failures without having to re-push

chore: always run both tf lint and fmt checks

---

.github/actions/lint-github-actions/action.yml

Custom runner labels should not cause a failure.
Tested here https://github.com/abcxyz/github-metrics-aggregator/pull/372

chore: ignore unknown runner labels

---

.github/actions/multi-approvers/README.md

The docs were referencing abcxyz/pkg instead of abcxyz/actions. `pkg` is
where the action was initially going to be submitted. But then we
decided to put it in `actions`. When the code was copied over, this
reference was not changed.

Fix references to multi-approvers action in docs

---

.github/actions/setup-binary/action.yml

Currently, setup-binary downloads `hashicorp/go-getter` on every workflow job since it refers to a non-existent step.

fix: setup-binary skip go-getter install on cache hit

---

.github/workflows/.lint-actions.yml
.github/workflows/lint.yml

File scanning did not work for certain repos. We were seeing flaky behavior on lumberjack and hackathon-infra. This fix updates the match_files to ignore exit codes from grep if we successfully found a match. It looks like sometimes grep would exit early and `git ls-tree` would continue to pipe results into it which would result in a nonzero exit code like 141. 
Tested here: https://github.com/abcxyz/lumberjack/actions/runs/14716955789/job/41302509496?pr=506

fix: file scanning

---

.github/actions/lint-shell/action.yml
.shellcheckrc

Arguably `cat file | command` is easier to read, as information flows from left to right.
This is especially true from something like jq, where the format is
`jq [some possibly quite long query string] file` where the file is the last positional argument.
rc file download uses pattern from yamllint action

Disable SC2002 -- useless use of cat, and add .shellcheckrc file

---

.github/actions/pull-request-lint/action.yml

This is why it's really really important to not pass inputs directly into the shell...
```text
This is a test
```
```script
even more of a test
```
`exit 0

pull_request_description: handle shell escapes

---

.github/actions/lint-go/action.yml
.github/actions/lint-yaml/action.yml
.github/workflows/.lint-actions.yml
.github/workflows/lint.yml
.github/workflows/multi-approvers.yml

Now that we have a lot of linters, this is really noisy:

Move most notice to debug to clean up logs

---

.github/actions/lint-github-actions/action.yml
.github/actions/lint-shell/action.yml

Install shellcheck from source for both the lint-shell and lint-github-actions actions. Enables us to add back the shellcheckrc https://github.com/abcxyz/actions/issues/60

chore: install shellcheck binary from source

---

.github/actions/want-lgtm/action.yml

Fix broken sort in want-lgtm-all workflow
This updates the sorting logic in the `Re-run Status Checks` step of want-lgtm-all workflow to accurately identify the latest failed workflow run by its `run_number`.
The previous sorting method `(x) => x.id` could result in unreliable sorting. The new logic `.sort((a, b) => b.run_number - a.run_number)` uses `run_number` as a direct sequential identifier for a specific workflow execution, ensuring that the most recently failed run is correctly selected for rerun attempts.
Issue link: https://github.com/abcxyz/pkg/issues/428

Fix sort in want-lgtm-all workflow

---

.github/actions/create-pull-request/action.yml

This fixes a bug when trying to `fs.stat` on deleted files in the commit, because the files no longer exist.

fix: remove fs.stat on deleted files for create-pull-request action

---

.github/actions/create-pull-request/action.yml

Optionally take repository as action input instead, falling back to `context.repo` whenever not specified instead of always assuming `context.repo`. 
This will be used by [LSC](https://github.com/abcxyz/lsc) to create PRs for multiple different repos from the same workflow.

Create PR Action: Allow caller to specify which repo the PR is for

---

.github/actions/multi-approvers/README.md

Update the docs to explain when and how to use `pull_request_target`
instead of `pull_request`.
Fixes #70

Update multi-approver docs to explain pull_request_target

---

.github/actions/multi-approvers/action.yml
.github/actions/multi-approvers/src/main.ts
.github/actions/multi-approvers/src/multi-approvers.ts
.github/actions/multi-approvers/tests/main.test.ts
.github/actions/multi-approvers/tests/multi-approvers.test.ts

Add an allowlist of GitHub user IDs that won't require multi-approvers when raising a PR.
This add a new input `allowlisted-user-ids` via action, which is an allowlist of trusted GitHub user IDs. It will be read and parsed into a Set. `MultiApproversAction` will check if the user in on the allowlist. If so, it won't trigger multi-approvers requirement like internal users.
Fixes #68

Add allowlist feature for multi-approvers

---

.github/actions/multi-approvers/src/multi-approvers.ts
.github/actions/multi-approvers/tests/multi-approvers.test.ts

This change allows the multi-approvers action to properly support
workflows that use the pull_request_target event.
See #68 for an explanation of the support for pull_request_target.
Fixes #78

Adds support for pull_request_target

---

.github/actions/lint-docker/action.yml
.github/actions/lint-java/action.yml
.github/actions/lint-shell/action.yml
.github/actions/lint-yaml/action.yml
.github/workflows/.lint-actions.yml
.github/workflows/lint.yml
.hadolint.yml

Uses hadolint to lint dockerfiles and updates all lint finding algorithms to use `git ls-files` so that .gitignores are respected.

chore: lint docker

---

.github/actions/create-pull-request/action.yml

Tested in another repo: https://github.com/porcupine/platform-gcp-infrastructure/actions/runs/15592168989/job/43913706692. Moved files only show up in the CHANGED files list. They must show up both in the CHANGED AND DELETED lists in order to properly be handled.
Before making this change modifications that resulted in a `moved file` were incorrectly committed as `added file` and the old files were not removed leading to file duplication.

chore: correctly handle file renames in create-pull-request

---

.github/actions/multi-approvers/src/main.ts
.github/actions/multi-approvers/tests/main.test.ts

This will handle situations when the input string is null, empty, or just whitespace. Add more tests as well.

fix: add more checks for multi approvers
